

```{r}
library(ggplot2)
library(ggthemes)
library(ggthemr)
library(reshape2)
library(tidyr)
library(circlize)
library(networkD3)
library(tidyverse)
library(scales)
library(ggstatsplot)
library(hrbrthemes)
library(plyr)
```

```{r}
df_cost_raw = read.xlsx("ResultSummary_2.xlsx", sheet = 2)
df_cost_raw$Scenarios <- as.factor(df_cost_raw$Scenarios)

perc = as.data.frame(paste(unlist(df_cost_raw$Percentage*100), '%', sep=''))

df_cost2 = cbind(df_cost_raw[,1:4],perc)
df_cost2[5][df_cost2[5] == "NA%"] <- NA
#a2
names(df_cost2)[1:5]<-c("Country","Scenarios","Category","Data","Percentage")
df_cost2
```

```{r}
India_Cost_2 = df_cost2[1:36,]
Bangladesh_Cost_2 = df_cost2[37:48,]
```

```{r}
pdf('CostIndia (s2).pdf')

CostCountryIndia2 <- ggplot(India_Cost_2, aes(x = Scenarios,y = Data, fill = Category)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Percentage), position = position_stack(vjust = 0.5)) +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India (s2)") 

CostCountryIndia2

dev.off()
```
```{r}
df_cost_raw = read.xlsx("ResultSummary_2.xlsx", sheet = 2)
df_cost_raw$Scenarios <- as.factor(df_cost_raw$Scenarios)

perc = as.data.frame(paste(unlist(df_cost_raw$Percentage*100), '%', sep=''))

df_cost2 = cbind(df_cost_raw[,1:4],perc)
df_cost2[5][df_cost2[5] == "NA%"] <- NA
#a2
names(df_cost2)[1:5]<-c("Country","Scenarios","Category","Data","Percentage")
df_cost2
```
```{r}

Index_category <- as.data.frame(unique(India_Cost_2[,3]))
Index_category
India_Cost_Var <- subset(India_Cost_2, India_Cost_2[,3]==Index_category[1,])
India_Cost_Fix <- subset(India_Cost_2, India_Cost_2[,3]==Index_category[2,])
India_Cost_USE <- subset(India_Cost_2, India_Cost_2[,3]==Index_category[3,])
India_Cost_USR <- subset(India_Cost_2, India_Cost_2[,3]==Index_category[4,])
India_Cost_Tran <- subset(India_Cost_2, India_Cost_2[,3]==Index_category[5,])
India_Cost_Curt <- subset(India_Cost_2, India_Cost_2[,3]==Index_category[6,])
India_Cost_Curt
```





```{r}
#pdf('CostIndiasubVar (s2).pdf')
#India_Cost_2$Scenarios <- factor(India_Cost_2$Scenarios, levels=c('Capacity = 1360MW', 'Capacity = 1960MW', 'Capacity = 2610MW', 'Capacity = 3710MW', 'Capacity = 6310MW',"Capacity = 17310MW"))


CostIndia_Cost_Var <- ggplot(India_Cost_Var, aes(x = Scenarios,y = Data, fill = Scenarios)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Data), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  ggtitle("Cost Summary of India - Variable O&M Cost (s2)") +
  #scale_fill_manual(breaks=c("1360", "1960", "2610", "3710", "6310", "17310"),labels=c('Capacity = 1360MW', 'Capacity = 1960MW', 'Capacity = 2610MW', 'Capacity = 3710MW', 'Capacity = 6310MW',"Capacity = 17310MW"),values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue"))+
  guides(fill=FALSE)

CostIndia_Cost_Var

#dev.off()
```
```{r}
pdf('CostIndiasubFix (s2).pdf')

CostIndia_Cost_Fix <- ggplot(India_Cost_Fix, aes(x = Scenarios,y = Data, fill = Scenarios)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Data), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India - Fixed Cost (s2)") +
  guides(fill=FALSE)

CostIndia_Cost_Fix

dev.off()
```
```{r}
pdf('CostIndiasubUSE (s2).pdf')

CostIndia_Cost_USE <- ggplot(India_Cost_USE, aes(x = Scenarios,y = Data, fill = Scenarios)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Data), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India - USE Cost (s2)") +
  guides(fill=FALSE)

CostIndia_Cost_USE

dev.off()
```

```{r}
pdf('CostIndiasubUSR (s2).pdf')

CostIndia_Cost_USR <- ggplot(India_Cost_USR, aes(x = Scenarios,y = Data, fill = Scenarios)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Data), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India - USR Cost (s2)") +
  guides(fill=FALSE)

CostIndia_Cost_USR

dev.off()
```

```{r}
pdf('CostIndiasubTran (s2).pdf')

CostIndia_Cost_Tran <- ggplot(India_Cost_Tran, aes(x = Scenarios,y = Data, fill = Scenarios)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Data), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India - Transmission Additions Cost (s2)") +
  guides(fill=FALSE)

CostIndia_Cost_Tran

dev.off()
```

```{r}
pdf('CostIndiasubCurt (s2).pdf')

CostIndia_Cost_Curt <- ggplot(India_Cost_Curt, aes(x = Scenarios,y = Data, fill = Scenarios)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Data), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India - Curtailment Cost (s2)") +
  guides(fill=FALSE)

CostIndia_Cost_Curt

dev.off()
```


```{r}
pdf('CostBangladesh (s2).pdf')

CostCountryBangladesh2 <- ggplot(Bangladesh_Cost_2, aes(x = Scenarios, y = Data, fill = Category)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("India-Bangladesh Line Capacity")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Percentage), position = position_stack(vjust = 0.5)) +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  scale_fill_manual(values=c("tan3", "skyblue"))  +
  ggtitle("Cost Summary of Bangladesh (s2)") 

CostCountryBangladesh2

dev.off()
```


```{r}
df_cost_raw1 = read.xlsx("ResultSummary_1.xlsx", sheet = 2)
df_cost_raw1$Scenarios <- as.factor(df_cost_raw1$Scenarios)

perc1 = as.data.frame(paste(unlist(df_cost_raw1$Percentage*100), '%', sep=''))

df_cost1 = cbind(df_cost_raw1[,1:4],perc1)
df_cost1[5][df_cost1[5] == "NA%"] <- NA
#a2
names(df_cost1)[1:5]<-c("Country","Scenarios","Category","Data","Percentage")
```
```{r}
Bangladesh_Cost_1 = df_cost1[1:4,]
Nepal_Cost_1 = df_cost1[5:9,]
SriLanka_Cost_1 = df_cost1[10:17,]
India_Cost_1 = df_cost1[18:47,]
```

```{r}
pdf('CostIndia (s1).pdf')

CostCountryIndia1 <- ggplot(India_Cost_1, aes(x = Scenarios, y = Data, fill = Category)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("Scenarios")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Percentage), position = position_stack(vjust = 0.5))  +
  scale_fill_manual(values=c("green4", "tan3", "slateblue3", "antiquewhite2","grey55","skyblue")) +
  ggtitle("Cost Summary of India (s1)") +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))

CostCountryIndia1

dev.off()
```

```{r}
pdf('CostBangladesh (s1).pdf')

CostCountryBangladesh1 <- ggplot(Bangladesh_Cost_1, aes(x = Scenarios, y = Data, fill = Category)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("Scenarios")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Percentage), position = position_stack(vjust = 0.5))  +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  scale_fill_manual(values=c("tan3","skyblue")) +
  ggtitle("Cost Summary of Bangladesh (s1)") 

CostCountryBangladesh1

dev.off()
```
```{r}
pdf('CostNepal (s1).pdf')

CostCountryNepal1 <- ggplot(Nepal_Cost_1, aes(x = Scenarios, y = Data, fill = Category)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("Scenarios")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Percentage), position = position_stack(vjust = 0.5))  +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  scale_fill_manual(values=c("tan3","antiquewhite2","grey55")) +
  ggtitle("Cost Summary of Nepal (s1)") 

CostCountryNepal1

dev.off()
```

```{r}
pdf('CostSriLanka (s1).pdf')

CostCountrySriLanka1 <- ggplot(SriLanka_Cost_1, aes(x = Scenarios, y = Data, fill = Category)) + 
  geom_bar(stat = "identity", position="stack")+
  xlab("Scenarios")+
  ylab("Cost ($B)") +
  #ggtitle ("SriLanka") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(~Scenarios) +
  geom_text(aes(label = Percentage), position = position_stack(vjust = 0.5))  +
  stat_summary(fun = sum, aes(label = round(..y.., digits = 0), group = Scenarios), geom = "text", size=3, vjust = -0.5)+
  scale_fill_manual(values=c("green4", "tan3", "grey55","skyblue")) +
  ggtitle("Cost Summary of SriLanka (s1)") 

CostCountrySriLanka1

dev.off()
```

```{r}
df_u = read.xlsx("ResultSummary_2.xlsx", sheet = 3)
df_u
names(df_u)[1:3]<-c("Year","Scenarios","Data")
df_u$Scenarios <- as.factor(df_u$Scenarios)
df_u[is.na(df_u)]<-0
df_u$Scenarios <- factor(df_u$Scenarios, levels=c('Capacity = 1360MW', 'Capacity = 1960MW', 'Capacity = 2610MW', 'Capacity = 3710MW', 'Capacity = 6310MW',"Capacity = 17310MW"))
df_u
```
```{r}
pdf('Utilization.pdf')

Utilization <- ggplot(df_u,aes(x = Year, y = Data, group = Scenarios, fill = Data, colour = Scenarios))+ 
      theme_minimal() +
			geom_line(size =0.8) +
      scale_color_manual(values=c("green4", "tan3", "lightpink3", "navyblue","grey55","skyblue")) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))+
      xlab("Year") +
      ylab("Line Utilization (%)") +
      ggtitle("India-Bangladesh Transmission Line Utilization") +
      theme(plot.title = element_text(hjust = 0.5)) 
Utilization

dev.off()
```

#Interchange
```{r}
Interchange_raw = read.csv("C:/Users/Mengqi Zhang/Research/R/graphs/Interchange.csv",head=T,sep=",")
Interchange_raw1 = Interchange_raw[,1:3]
Interchange <- na.omit(Interchange_raw1)
Interchange
```
```{r}
colnames(Interchange) <- c("source", "target", "value")
Interchange$target <- paste(Interchange$target, " ", sep = "")

nodes <- data.frame(name = c(as.character(Interchange$source), as.character(Interchange$target)) %>% unique()) %>% arrange(name) %>% as.data.frame()
Interchange$IDsource = match(Interchange$source, nodes$name) - 1 
Interchange$IDtarget = match(Interchange$target, nodes$name) - 1
ColourScal='d3.scaleOrdinal() .range(["#954A45","#86473F","#FEDFE1","#BF6766","#554236","#D7C4BB",   "#B19693","DB8E71"])'


sankeyNetwork(Links = Interchange, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              sinksRight=FALSE, colourScale=ColourScal, nodeWidth=40, fontSize=13, nodePadding=20)
```
```{r}
#jpeg(file="Interchange_ChordDiagram.jpeg", width = 4000, height = 3500, res = 1000)

chordDiagram(Interchange) #+ geom_text_repel()
circos.clear()

#dev.off()
```

```{r}
Interchange1 = read.csv("C:/Users/Mengqi Zhang/Research/R/graphs/Interchange1.csv",head=T,sep=",")
names(Interchange1)[1:2]<-c("Country","India")
Interchange1
```
```{r}
#jpeg(file="Interchange1.jpeg")

Interchange_plot1 <- ggplot(Interchange1, aes(Country, X2018)) +
  geom_bar(stat="identity") +
  ggtitle("Cross-Border Transmission") +
  xlab("Zone") + 
  ylab("Annual Export to/Import from India (GWh)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_text(aes(label = X2018), position = position_stack(vjust = 0.5))

  ggthemr('dust')
  Interchange_plot1
  
#dev.off()
```